In [285]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import datetime

import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
import urllib.request

#Импортируем нужные библиотеки:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import linear_model
from sklearn.cluster import KMeans
from sklearn import cross_validation
from sklearn import metrics 
from pandas import DataFrame
%pylab inline

Populating the interactive namespace from numpy and matplotlib

/anaconda3/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['random']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

In [286]:
raw_df = pd.read_csv('https://raw.githubusercontent.com/netology-code/data-scientist4/master/3.%20Python%20Preprocessing/Python%20Preprocessing%20-%20Laboratory%20Work/data.csv', 'r', delimiter=";")

In [287]:
raw_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SaleCategory
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,1
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,1
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,1

In [288]:
raw_df.MSZoning.value_counts()

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

In [289]:
raw_df.MSSubClass.value_counts()

20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64

In [290]:
#SaleCondition разбить на дамми-переменные
#Utilities: Type of utilities available разбить на дамми-переменные
#BldgType: Type of dwelling
# OverallQual: Rates the overall material and finish of the house
#OverallCond: Rates the overall condition of the house
#ExterCond: Evaluates the present condition of the material on the exterior
# BsmtExposure: Refers to walkout or garden level walls

#LotArea: Lot size in square feet-add
#MasVnrArea: Masonry veneer area in square feet
# TotalBsmtSF: Total square feet of basement area
#SaleCondition: Condition of sale разбить на дамми-переменные

In [291]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SaleCategory     1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [292]:
raw_df.shape

(1460, 81)

In [293]:
raw_df=raw_df.drop(raw_df.columns[[0,2,3,5,6,7,8,9,10,11,12,14,16,19,20,21,22,23,24,25,29,30,31,33,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77]],1)

In [294]:
raw_df.head()

,MSSubClass,LotArea,Condition1,BldgType,OverallQual,OverallCond,MasVnrArea,ExterQual,ExterCond,BsmtExposure,TotalBsmtSF,SaleType,SaleCondition,SaleCategory
0,60,8450,Norm,1Fam,7,5,196.0,Gd,TA,No,856,WD,Normal,1
1,20,9600,Feedr,1Fam,6,8,0.0,TA,TA,Gd,1262,WD,Normal,0
2,60,11250,Norm,1Fam,7,5,162.0,Gd,TA,Mn,920,WD,Normal,1
3,70,9550,Norm,1Fam,7,5,0.0,TA,TA,No,756,WD,Abnorml,0
4,60,14260,Norm,1Fam,8,5,350.0,Gd,TA,Av,1145,WD,Normal,1

In [295]:
raw_df.info

<bound method DataFrame.info of       MSSubClass  LotArea Condition1 BldgType  OverallQual  OverallCond  \
0             60     8450       Norm     1Fam            7            5
1             20     9600      Feedr     1Fam            6            8
2             60    11250       Norm     1Fam            7            5
3             70     9550       Norm     1Fam            7            5
4             60    14260       Norm     1Fam            8            5
5             50    14115       Norm     1Fam            5            5
6             20    10084       Norm     1Fam            8            5
7             60    10382       PosN     1Fam            7            6
8             50     6120     Artery     1Fam            7            5
9            190     7420     Artery   2fmCon            5            6
10            20    11200       Norm     1Fam            5            5
11            60    11924       Norm     1Fam            9            5
12            20    12968       Norm     1Fam            5            6
13            20    10652       Norm     1Fam            7            5
14            20    10920       Norm     1Fam            6            5
15            45     6120       Norm     1Fam            7            8
16            20    11241       Norm     1Fam            6            7
17            90    10791       Norm   Duplex            4            5
18            20    13695       RRAe     1Fam            5            5
19            20     7560       Norm     1Fam            5            6
20            60    14215       Norm     1Fam            8            5
21            45     7449       Norm     1Fam            7            7
22            20     9742       Norm     1Fam            8            5
23           120     4224       Norm   TwnhsE            5            7
24            20     8246       Norm     1Fam            5            8
25            20    14230       Norm     1Fam            8            5
26            20     7200       Norm     1Fam            5            7
27            20    11478       Norm     1Fam            8            5
28            20    16321       Norm     1Fam            5            6
29            30     6324      Feedr     1Fam            4            6
...          ...      ...        ...      ...          ...          ...
1430          60    21930       RRAn     1Fam            5            5
1431         120     4928       Norm   TwnhsE            6            6
1432          30    10800       Norm     1Fam            4            6
1433          60    10261       Norm     1Fam            6            5
1434          20    17400       Norm     1Fam            5            5
1435          20     8400       Norm     1Fam            6            9
1436          20     9000       Norm     1Fam            4            6
1437          20    12444       Norm     1Fam            8            5
1438          20     7407     Artery     1Fam            6            7
1439          60    11584       Norm     1Fam            7            6
1440          70    11526       Norm     1Fam            6            7
1441         120     4426       Norm   TwnhsE            6            5
1442          60    11003       Norm     1Fam           10            5
1443          30     8854       Norm     1Fam            6            6
1444          20     8500       Norm     1Fam            7            5
1445          85     8400       Norm     1Fam            6            5
1446          20    26142       Norm     1Fam            5            7
1447          60    10000       Norm     1Fam            8            5
1448          50    11767       Norm     1Fam            4            7
1449         180     1533       Norm    Twnhs            5            7
1450          90     9000       Norm   Duplex            5            5
1451          20     9262       Norm     1Fam            8            5
1452         180     3675       Norm   TwnhsE            5            5
1453          20    17217       Norm     1Fam            5            5
1454          20     7500       Norm     1Fam            7            5
1455          60     7917       Norm     1Fam            6            5
1456          20    13175       Norm     1Fam            6            6
1457          70     9042       Norm     1Fam            7            9
1458          20     9717       Norm     1Fam            5            6
1459          20     9937       Norm     1Fam            5            6

      MasVnrArea ExterQual ExterCond BsmtExposure  TotalBsmtSF SaleType  \
0          196.0        Gd        TA           No          856       WD
1            0.0        TA        TA           Gd         1262       WD
2          162.0        Gd        TA           Mn          920       WD
3            0.0        TA        TA           No          756       WD
4          350.0        Gd        TA           Av         1145       WD
5            0.0        TA        TA           No          796       WD
6          186.0        Gd        TA           Av         1686       WD
7          240.0        TA        TA           Mn         1107       WD
8            0.0        TA        TA           No          952       WD
9            0.0        TA        TA           No          991       WD
10           0.0        TA        TA           No         1040       WD
11         286.0        Ex        TA           No         1175      New
12           0.0        TA        TA           No          912       WD
13         306.0        Gd        TA           Av         1494      New
14         212.0        TA        TA           No         1253       WD
15           0.0        TA        TA           No          832       WD
16         180.0        TA        TA           No         1004       WD
17           0.0        TA        TA          NaN            0       WD
18           0.0        TA        TA           No         1114       WD
19           0.0        TA        TA           No         1029      COD
20         380.0        Gd        TA           Av         1158      New
21           0.0        TA        TA           No          637       WD
22         281.0        Gd        TA           No         1777       WD
23           0.0        TA        TA           No         1040       WD
24           0.0        TA        Gd           Mn         1060       WD
25         640.0        Gd        TA           No         1566       WD
26           0.0        TA        TA           Mn          900       WD
27         200.0        Gd        TA           No         1704       WD
28           0.0        TA        TA           Gd         1484       WD
29           0.0        TA        TA           No          520       WD
...          ...       ...       ...          ...          ...      ...
1430         0.0        Gd        TA           Av          732       WD
1431         0.0        TA        TA           No          958       WD
1432         0.0        TA        TA           No          656       WD
1433       318.0        TA        TA           No          936       WD
1434         0.0        TA        TA           No         1126       WD
1435       237.0        Gd        Gd           No         1319      COD
1436         0.0        TA        TA           No          864       WD
1437       426.0        Ex        TA           Av         1932      New
1438         0.0        TA        TA           No          912       WD
1439        96.0        TA        TA           No          539       WD
1440         0.0        TA        TA           No          588       WD
1441       147.0        Gd        TA           Av          848       WD
1442       160.0        Ex        TA           Av         1017       WD
1443         0.0        TA        TA           No          952       WD
1444       106.0        Gd        TA           Av         1422       WD
1445         0.0        TA        TA           Gd          814       WD
1446       189.0        TA        TA           No         1188       WD
1447       438.0        Gd        TA           No         1220       WD
1448         0.0        TA        TA           No          560       WD
1449         0.0        TA        TA           Av          630       WD
1450         0.0        TA        TA           No          896       WD
1451       194.0        Gd        TA           No         1573      New
1452        80.0        TA        TA           Gd          547       WD
1453         0.0        TA        TA           No         1140       WD
1454         0.0        Gd        TA           No         1221       WD
1455         0.0        TA        TA           No          953       WD
1456       119.0        TA        TA           No         1542       WD
1457         0.0        Ex        Gd           No         1152       WD
1458         0.0        TA        TA           Mn         1078       WD
1459         0.0        Gd        TA           No         1256       WD

     SaleCondition  SaleCategory
0           Normal             1
1           Normal             0
2           Normal             1
3          Abnorml             0
4           Normal             1
5           Normal             0
6           Normal             1
7           Normal             1
8          Abnorml             0
9           Normal             0
10          Normal             0
11         Partial             1
12          Normal             0
13         Partial             1
14          Normal             0
15          Normal             0
16          Normal             0
17          Normal             0
18          Normal             0
19         Abnorml             0
20         Partial             1
21          Normal             0
22          Normal             1
23          Normal             0
24          Normal             0
25          Normal             1
26          Normal             0
27          Normal             1
28          Normal             1
29          Normal             0
...            ...           ...
1430        Normal             0
1431        Normal             0
1432        Normal             0
1433        Normal             0
1434        Normal             0
1435       Abnorml             0
1436        Normal             0
1437       Partial             1
1438        Normal             0
1439        Normal             0
1440        Normal             0
1441        Normal             0
1442        Normal             1
1443        Normal             0
1444        Normal             0
1445        Normal             0
1446        Normal             0
1447        Normal             1
1448        Normal             0
1449       Abnorml             0
1450        Normal             0
1451       Partial             1
1452        Normal             0
1453       Abnorml             0
1454        Normal             0
1455        Normal             0
1456        Normal             1
1457        Normal             1
1458        Normal             0
1459        Normal             0

[1460 rows x 14 columns]>

In [296]:
print("Исходные признаки:\n", list(raw_df.columns), "\n") 
data_dummies = pd.get_dummies(raw_df)
data_dummies=data_dummies.drop(['SaleCategory'],1)
print("Признаки после get_dummies:\n", list(data_dummies.columns))

Исходные признаки:
 ['MSSubClass', 'LotArea', 'Condition1', 'BldgType', 'OverallQual', 'OverallCond', 'MasVnrArea', 'ExterQual', 'ExterCond', 'BsmtExposure', 'TotalBsmtSF', 'SaleType', 'SaleCondition', 'SaleCategory']

Признаки после get_dummies:
 ['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'MasVnrArea', 'TotalBsmtSF', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'BldgType_1Fam', 'BldgType_2fmCon', 'BldgType_Duplex', 'BldgType_Twnhs', 'BldgType_TwnhsE', 'ExterQual_Ex', 'ExterQual_Fa', 'ExterQual_Gd', 'ExterQual_TA', 'ExterCond_Ex', 'ExterCond_Fa', 'ExterCond_Gd', 'ExterCond_Po', 'ExterCond_TA', 'BsmtExposure_Av', 'BsmtExposure_Gd', 'BsmtExposure_Mn', 'BsmtExposure_No', 'SaleType_COD', 'SaleType_CWD', 'SaleType_Con', 'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial']

In [297]:
data_dummies

,MSSubClass,LotArea,OverallQual,OverallCond,MasVnrArea,TotalBsmtSF,Condition1_Artery,Condition1_Feedr,Condition1_Norm,Condition1_PosA,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,8450,7,5,196.0,856,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1,20,9600,6,8,0.0,1262,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,60,11250,7,5,162.0,920,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
3,70,9550,7,5,0.0,756,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
4,60,14260,8,5,350.0,1145,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
5,50,14115,5,5,0.0,796,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
6,20,10084,8,5,186.0,1686,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
7,60,10382,7,6,240.0,1107,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
8,50,6120,7,5,0.0,952,1,0,0,0,...,0,0,0,1,1,0,0,0,0,0
9,190,7420,5,6,0.0,991,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
10,20,11200,5,5,0.0,1040,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
11,60,11924,9,5,286.0,1175,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
12,20,12968,5,6,0.0,912,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
13,20,10652,7,5,306.0,1494,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
14,20,10920,6,5,212.0,1253,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
15,45,6120,7,8,0.0,832,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
16,20,11241,6,7,180.0,1004,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
17,90,10791,4,5,0.0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
18,20,13695,5,5,0.0,1114,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
19,20,7560,5,6,0.0,1029,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
20,60,14215,8,5,380.0,1158,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
21,45,7449,7,7,0.0,637,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
22,20,9742,8,5,281.0,1777,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
23,120,4224,5,7,0.0,1040,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
24,20,8246,5,8,0.0,1060,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
25,20,14230,8,5,640.0,1566,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
26,20,7200,5,7,0.0,900,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
27,20,11478,8,5,200.0,1704,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
28,20,16321,5,6,0.0,1484,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
29,30,6324,4,6,0.0,520,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,21930,5,5,0.0,732,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1431,120,4928,6,6,0.0,958,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1432,30,10800,4,6,0.0,656,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1433,60,10261,6,5,318.0,936,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1434,20,17400,5,5,0.0,1126,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1435,20,8400,6,9,237.0,1319,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1436,20,9000,4,6,0.0,864,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1437,20,12444,8,5,426.0,1932,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
1438,20,7407,6,7,0.0,912,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1439,60,11584,7,6,96.0,539,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1440,70,11526,6,7,0.0,588,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1441,120,4426,6,5,147.0,848,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1442,60,11003,10,5,160.0,1017,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1443,30,8854,6,6,0.0,952,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1444,20,8500,7,5,106.0,1422,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1445,85,8400,6,5,0.0,814,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1446,20,26142,5,7,189.0,1188,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1447,60,10000,8,5,438.0,1220,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1448,50,11767,4,7,0.0,560,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1449,180,1533,5,7,0.0,630,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
1450,90,9000,5,5,0.0,896,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1451,20,9262,8,5,194.0,1573,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
1452,180,3675,5,5,80.0,547,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1453,20,17217,5,5,0.0,1140,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
1454,20,7500,7,5,0.0,1221,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1455,60,7917,6,5,0.0,953,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,13175,6,6,119.0,1542,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1457,70,9042,7,9,0.0,1152,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,9717,5,6,0.0,1078,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1459,20,9937,5,6,0.0,1256,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0

In [298]:
raw_df.SaleCategory

0       1
1       0
2       1
3       0
4       1
5       0
6       1
7       1
8       0
9       0
10      0
11      1
12      0
13      1
14      0
15      0
16      0
17      0
18      0
19      0
20      1
21      0
22      1
23      0
24      0
25      1
26      0
27      1
28      1
29      0
       ..
1430    0
1431    0
1432    0
1433    0
1434    0
1435    0
1436    0
1437    1
1438    0
1439    0
1440    0
1441    0
1442    1
1443    0
1444    0
1445    0
1446    0
1447    1
1448    0
1449    0
1450    0
1451    1
1452    0
1453    0
1454    0
1455    0
1456    1
1457    1
1458    0
1459    0
Name: SaleCategory, Length: 1460, dtype: int64

In [305]:
features = data_dummies.ix[:, 'Condition1_Artery':'SaleCondition_Partial']
# Извлекаем массивы NumPy
X = features.values
y = raw_df['SaleCategory'].values
print("форма массива X: {} форма массива y: {}".format(X.shape, y.shape))

форма массива X: (1460, 42) форма массива y: (1460,)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [329]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(features, raw_df[['SaleCategory']], test_size = 0.3, random_state = 0)
model = linear_model.SGDClassifier(alpha=0.0001, n_iter=100, random_state = 0)
model.fit(train_data, train_labels)
model_predictions = model.predict(test_data)
print (metrics.accuracy_score(test_labels, model_predictions))
print (metrics.classification_report(test_labels, model_predictions))

0.8447488584474886
             precision    recall  f1-score   support

          0       0.90      0.88      0.89       312
          1       0.71      0.77      0.74       126

avg / total       0.85      0.84      0.85       438

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [330]:
train_data.shape

(1022, 42)

In [331]:
raw_df.SaleCategory.value_counts()

0    1025
1     435
Name: SaleCategory, dtype: int64

In [332]:
test_data.shape

(438, 42)

In [335]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(features, raw_df[['SaleCategory']], test_size = 0.3, random_state = 0)
model = linear_model.SGDClassifier(alpha=0.001, n_iter=100, random_state = 0)
model.fit(train_data, train_labels)
model_predictions = model.predict(test_data)
print (metrics.accuracy_score(test_labels, model_predictions))
print (metrics.classification_report(test_labels, model_predictions))

0.8424657534246576
             precision    recall  f1-score   support

          0       0.90      0.88      0.89       312
          1       0.71      0.76      0.74       126

avg / total       0.85      0.84      0.84       438

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [338]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(features, raw_df['SaleCategory'], test_size = 0.3)
model = linear_model.SGDClassifier(alpha=0.0009, n_iter=96, random_state = 0)
scores = cross_validation.cross_val_score(model, train_data, train_labels, cv=10)
print (scores.mean())

0.8306871321055578

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)